# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/xuhao/nettest/spdnet/spdnet

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/xuhao/nettest/spdnet/spdnet

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xuhao/nettest/spdnet/spdnet/CMakeFiles /home/xuhao/nettest/spdnet/spdnet/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xuhao/nettest/spdnet/spdnet/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named spdnet

# Build rule for target.
spdnet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 spdnet
.PHONY : spdnet

# fast build rule for target.
spdnet/fast:
	$(MAKE) -f CMakeFiles/spdnet.dir/build.make CMakeFiles/spdnet.dir/build
.PHONY : spdnet/fast

#=============================================================================
# Target rules for targets named pingpongclient

# Build rule for target.
pingpongclient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pingpongclient
.PHONY : pingpongclient

# fast build rule for target.
pingpongclient/fast:
	$(MAKE) -f examples/CMakeFiles/pingpongclient.dir/build.make examples/CMakeFiles/pingpongclient.dir/build
.PHONY : pingpongclient/fast

#=============================================================================
# Target rules for targets named pingpongserver

# Build rule for target.
pingpongserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pingpongserver
.PHONY : pingpongserver

# fast build rule for target.
pingpongserver/fast:
	$(MAKE) -f examples/CMakeFiles/pingpongserver.dir/build.make examples/CMakeFiles/pingpongserver.dir/build
.PHONY : pingpongserver/fast

#=============================================================================
# Target rules for targets named ttcp_client

# Build rule for target.
ttcp_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ttcp_client
.PHONY : ttcp_client

# fast build rule for target.
ttcp_client/fast:
	$(MAKE) -f examples/CMakeFiles/ttcp_client.dir/build.make examples/CMakeFiles/ttcp_client.dir/build
.PHONY : ttcp_client/fast

#=============================================================================
# Target rules for targets named ttcp_server

# Build rule for target.
ttcp_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ttcp_server
.PHONY : ttcp_server

# fast build rule for target.
ttcp_server/fast:
	$(MAKE) -f examples/CMakeFiles/ttcp_server.dir/build.make examples/CMakeFiles/ttcp_server.dir/build
.PHONY : ttcp_server/fast

src/spdnet/base/buffer.o: src/spdnet/base/buffer.cc.o
.PHONY : src/spdnet/base/buffer.o

# target to build an object file
src/spdnet/base/buffer.cc.o:
	$(MAKE) -f CMakeFiles/spdnet.dir/build.make CMakeFiles/spdnet.dir/src/spdnet/base/buffer.cc.o
.PHONY : src/spdnet/base/buffer.cc.o

src/spdnet/base/buffer.i: src/spdnet/base/buffer.cc.i
.PHONY : src/spdnet/base/buffer.i

# target to preprocess a source file
src/spdnet/base/buffer.cc.i:
	$(MAKE) -f CMakeFiles/spdnet.dir/build.make CMakeFiles/spdnet.dir/src/spdnet/base/buffer.cc.i
.PHONY : src/spdnet/base/buffer.cc.i

src/spdnet/base/buffer.s: src/spdnet/base/buffer.cc.s
.PHONY : src/spdnet/base/buffer.s

# target to generate assembly for a file
src/spdnet/base/buffer.cc.s:
	$(MAKE) -f CMakeFiles/spdnet.dir/build.make CMakeFiles/spdnet.dir/src/spdnet/base/buffer.cc.s
.PHONY : src/spdnet/base/buffer.cc.s

src/spdnet/base/current_thread.o: src/spdnet/base/current_thread.cc.o
.PHONY : src/spdnet/base/current_thread.o

# target to build an object file
src/spdnet/base/current_thread.cc.o:
	$(MAKE) -f CMakeFiles/spdnet.dir/build.make CMakeFiles/spdnet.dir/src/spdnet/base/current_thread.cc.o
.PHONY : src/spdnet/base/current_thread.cc.o

src/spdnet/base/current_thread.i: src/spdnet/base/current_thread.cc.i
.PHONY : src/spdnet/base/current_thread.i

# target to preprocess a source file
src/spdnet/base/current_thread.cc.i:
	$(MAKE) -f CMakeFiles/spdnet.dir/build.make CMakeFiles/spdnet.dir/src/spdnet/base/current_thread.cc.i
.PHONY : src/spdnet/base/current_thread.cc.i

src/spdnet/base/current_thread.s: src/spdnet/base/current_thread.cc.s
.PHONY : src/spdnet/base/current_thread.s

# target to generate assembly for a file
src/spdnet/base/current_thread.cc.s:
	$(MAKE) -f CMakeFiles/spdnet.dir/build.make CMakeFiles/spdnet.dir/src/spdnet/base/current_thread.cc.s
.PHONY : src/spdnet/base/current_thread.cc.s

src/spdnet/base/socket_api.o: src/spdnet/base/socket_api.cc.o
.PHONY : src/spdnet/base/socket_api.o

# target to build an object file
src/spdnet/base/socket_api.cc.o:
	$(MAKE) -f CMakeFiles/spdnet.dir/build.make CMakeFiles/spdnet.dir/src/spdnet/base/socket_api.cc.o
.PHONY : src/spdnet/base/socket_api.cc.o

src/spdnet/base/socket_api.i: src/spdnet/base/socket_api.cc.i
.PHONY : src/spdnet/base/socket_api.i

# target to preprocess a source file
src/spdnet/base/socket_api.cc.i:
	$(MAKE) -f CMakeFiles/spdnet.dir/build.make CMakeFiles/spdnet.dir/src/spdnet/base/socket_api.cc.i
.PHONY : src/spdnet/base/socket_api.cc.i

src/spdnet/base/socket_api.s: src/spdnet/base/socket_api.cc.s
.PHONY : src/spdnet/base/socket_api.s

# target to generate assembly for a file
src/spdnet/base/socket_api.cc.s:
	$(MAKE) -f CMakeFiles/spdnet.dir/build.make CMakeFiles/spdnet.dir/src/spdnet/base/socket_api.cc.s
.PHONY : src/spdnet/base/socket_api.cc.s

src/spdnet/net/channel.o: src/spdnet/net/channel.cc.o
.PHONY : src/spdnet/net/channel.o

# target to build an object file
src/spdnet/net/channel.cc.o:
	$(MAKE) -f CMakeFiles/spdnet.dir/build.make CMakeFiles/spdnet.dir/src/spdnet/net/channel.cc.o
.PHONY : src/spdnet/net/channel.cc.o

src/spdnet/net/channel.i: src/spdnet/net/channel.cc.i
.PHONY : src/spdnet/net/channel.i

# target to preprocess a source file
src/spdnet/net/channel.cc.i:
	$(MAKE) -f CMakeFiles/spdnet.dir/build.make CMakeFiles/spdnet.dir/src/spdnet/net/channel.cc.i
.PHONY : src/spdnet/net/channel.cc.i

src/spdnet/net/channel.s: src/spdnet/net/channel.cc.s
.PHONY : src/spdnet/net/channel.s

# target to generate assembly for a file
src/spdnet/net/channel.cc.s:
	$(MAKE) -f CMakeFiles/spdnet.dir/build.make CMakeFiles/spdnet.dir/src/spdnet/net/channel.cc.s
.PHONY : src/spdnet/net/channel.cc.s

src/spdnet/net/connector.o: src/spdnet/net/connector.cc.o
.PHONY : src/spdnet/net/connector.o

# target to build an object file
src/spdnet/net/connector.cc.o:
	$(MAKE) -f CMakeFiles/spdnet.dir/build.make CMakeFiles/spdnet.dir/src/spdnet/net/connector.cc.o
.PHONY : src/spdnet/net/connector.cc.o

src/spdnet/net/connector.i: src/spdnet/net/connector.cc.i
.PHONY : src/spdnet/net/connector.i

# target to preprocess a source file
src/spdnet/net/connector.cc.i:
	$(MAKE) -f CMakeFiles/spdnet.dir/build.make CMakeFiles/spdnet.dir/src/spdnet/net/connector.cc.i
.PHONY : src/spdnet/net/connector.cc.i

src/spdnet/net/connector.s: src/spdnet/net/connector.cc.s
.PHONY : src/spdnet/net/connector.s

# target to generate assembly for a file
src/spdnet/net/connector.cc.s:
	$(MAKE) -f CMakeFiles/spdnet.dir/build.make CMakeFiles/spdnet.dir/src/spdnet/net/connector.cc.s
.PHONY : src/spdnet/net/connector.cc.s

src/spdnet/net/event_loop.o: src/spdnet/net/event_loop.cc.o
.PHONY : src/spdnet/net/event_loop.o

# target to build an object file
src/spdnet/net/event_loop.cc.o:
	$(MAKE) -f CMakeFiles/spdnet.dir/build.make CMakeFiles/spdnet.dir/src/spdnet/net/event_loop.cc.o
.PHONY : src/spdnet/net/event_loop.cc.o

src/spdnet/net/event_loop.i: src/spdnet/net/event_loop.cc.i
.PHONY : src/spdnet/net/event_loop.i

# target to preprocess a source file
src/spdnet/net/event_loop.cc.i:
	$(MAKE) -f CMakeFiles/spdnet.dir/build.make CMakeFiles/spdnet.dir/src/spdnet/net/event_loop.cc.i
.PHONY : src/spdnet/net/event_loop.cc.i

src/spdnet/net/event_loop.s: src/spdnet/net/event_loop.cc.s
.PHONY : src/spdnet/net/event_loop.s

# target to generate assembly for a file
src/spdnet/net/event_loop.cc.s:
	$(MAKE) -f CMakeFiles/spdnet.dir/build.make CMakeFiles/spdnet.dir/src/spdnet/net/event_loop.cc.s
.PHONY : src/spdnet/net/event_loop.cc.s

src/spdnet/net/socket.o: src/spdnet/net/socket.cc.o
.PHONY : src/spdnet/net/socket.o

# target to build an object file
src/spdnet/net/socket.cc.o:
	$(MAKE) -f CMakeFiles/spdnet.dir/build.make CMakeFiles/spdnet.dir/src/spdnet/net/socket.cc.o
.PHONY : src/spdnet/net/socket.cc.o

src/spdnet/net/socket.i: src/spdnet/net/socket.cc.i
.PHONY : src/spdnet/net/socket.i

# target to preprocess a source file
src/spdnet/net/socket.cc.i:
	$(MAKE) -f CMakeFiles/spdnet.dir/build.make CMakeFiles/spdnet.dir/src/spdnet/net/socket.cc.i
.PHONY : src/spdnet/net/socket.cc.i

src/spdnet/net/socket.s: src/spdnet/net/socket.cc.s
.PHONY : src/spdnet/net/socket.s

# target to generate assembly for a file
src/spdnet/net/socket.cc.s:
	$(MAKE) -f CMakeFiles/spdnet.dir/build.make CMakeFiles/spdnet.dir/src/spdnet/net/socket.cc.s
.PHONY : src/spdnet/net/socket.cc.s

src/spdnet/net/tcp_connection.o: src/spdnet/net/tcp_connection.cc.o
.PHONY : src/spdnet/net/tcp_connection.o

# target to build an object file
src/spdnet/net/tcp_connection.cc.o:
	$(MAKE) -f CMakeFiles/spdnet.dir/build.make CMakeFiles/spdnet.dir/src/spdnet/net/tcp_connection.cc.o
.PHONY : src/spdnet/net/tcp_connection.cc.o

src/spdnet/net/tcp_connection.i: src/spdnet/net/tcp_connection.cc.i
.PHONY : src/spdnet/net/tcp_connection.i

# target to preprocess a source file
src/spdnet/net/tcp_connection.cc.i:
	$(MAKE) -f CMakeFiles/spdnet.dir/build.make CMakeFiles/spdnet.dir/src/spdnet/net/tcp_connection.cc.i
.PHONY : src/spdnet/net/tcp_connection.cc.i

src/spdnet/net/tcp_connection.s: src/spdnet/net/tcp_connection.cc.s
.PHONY : src/spdnet/net/tcp_connection.s

# target to generate assembly for a file
src/spdnet/net/tcp_connection.cc.s:
	$(MAKE) -f CMakeFiles/spdnet.dir/build.make CMakeFiles/spdnet.dir/src/spdnet/net/tcp_connection.cc.s
.PHONY : src/spdnet/net/tcp_connection.cc.s

src/spdnet/net/tcp_service.o: src/spdnet/net/tcp_service.cc.o
.PHONY : src/spdnet/net/tcp_service.o

# target to build an object file
src/spdnet/net/tcp_service.cc.o:
	$(MAKE) -f CMakeFiles/spdnet.dir/build.make CMakeFiles/spdnet.dir/src/spdnet/net/tcp_service.cc.o
.PHONY : src/spdnet/net/tcp_service.cc.o

src/spdnet/net/tcp_service.i: src/spdnet/net/tcp_service.cc.i
.PHONY : src/spdnet/net/tcp_service.i

# target to preprocess a source file
src/spdnet/net/tcp_service.cc.i:
	$(MAKE) -f CMakeFiles/spdnet.dir/build.make CMakeFiles/spdnet.dir/src/spdnet/net/tcp_service.cc.i
.PHONY : src/spdnet/net/tcp_service.cc.i

src/spdnet/net/tcp_service.s: src/spdnet/net/tcp_service.cc.s
.PHONY : src/spdnet/net/tcp_service.s

# target to generate assembly for a file
src/spdnet/net/tcp_service.cc.s:
	$(MAKE) -f CMakeFiles/spdnet.dir/build.make CMakeFiles/spdnet.dir/src/spdnet/net/tcp_service.cc.s
.PHONY : src/spdnet/net/tcp_service.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... spdnet"
	@echo "... pingpongclient"
	@echo "... pingpongserver"
	@echo "... ttcp_client"
	@echo "... ttcp_server"
	@echo "... src/spdnet/base/buffer.o"
	@echo "... src/spdnet/base/buffer.i"
	@echo "... src/spdnet/base/buffer.s"
	@echo "... src/spdnet/base/current_thread.o"
	@echo "... src/spdnet/base/current_thread.i"
	@echo "... src/spdnet/base/current_thread.s"
	@echo "... src/spdnet/base/socket_api.o"
	@echo "... src/spdnet/base/socket_api.i"
	@echo "... src/spdnet/base/socket_api.s"
	@echo "... src/spdnet/net/channel.o"
	@echo "... src/spdnet/net/channel.i"
	@echo "... src/spdnet/net/channel.s"
	@echo "... src/spdnet/net/connector.o"
	@echo "... src/spdnet/net/connector.i"
	@echo "... src/spdnet/net/connector.s"
	@echo "... src/spdnet/net/event_loop.o"
	@echo "... src/spdnet/net/event_loop.i"
	@echo "... src/spdnet/net/event_loop.s"
	@echo "... src/spdnet/net/socket.o"
	@echo "... src/spdnet/net/socket.i"
	@echo "... src/spdnet/net/socket.s"
	@echo "... src/spdnet/net/tcp_connection.o"
	@echo "... src/spdnet/net/tcp_connection.i"
	@echo "... src/spdnet/net/tcp_connection.s"
	@echo "... src/spdnet/net/tcp_service.o"
	@echo "... src/spdnet/net/tcp_service.i"
	@echo "... src/spdnet/net/tcp_service.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

